# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Experimenta con Jekyll
logo: /images/Logo.jpg
email: experimentaconjekyll@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lormez16.github.io/experimenta-con-jekyll/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lormez16
github_username:  lormez16

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Podcast Feed Settings
podcast_url: https://lormez16.github.io/experimenta-con-jekyll/
podcast_album_art: /images/Logo.jpg
podcast_title: Experimenta con Jekyll
podcast_owner: Laura
podcast_email: experimentaconjekyll@gmail.com
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_explicit: "no"
podcast_author: Laura
podcast_description: Podcast sobre Jekyll y la generación de blog estáticos.
podcast_summary: Podcast sobre Jekyll y la generación de blog estáticos. 
podcast_subtitle: Podcast sobre Jekyll y la generación de blog estáticos. 
